### ISSUE TITLE
Memory leaking when logging with `EspLogger`

### ISSUE THREAD

**Issue by kagetsuki1997** [esp-rs/esp-idf-svc#285]
I found out that the heap allocated bytes keep increasing when logging with `EspLogger`, then the program will crash when there is no free heap to use. I use `heap_caps_get_info` to observe the heap status.
Here are the dependencies
```toml
[dependencies]
log = { version = "0.4.17", default-features = false }
esp-idf-sys = { version = "0.33", default-features = false }
esp-idf-hal = { version = "0.41", optional = true, default-features = false }
esp-idf-svc = { version = "0.46", optional = true, default-features = false }
embedded-svc = { version = "0.25", optional = true, default-features = false }
embedded-hal = "=1.0.0-alpha.10"
```
```
ESP_IDF_VERSION: release/v5.1
Board type: nodemcu-32s
```

I did some tests and simulate on Wokwi, it seems like the problem is from `fwrite` https://github.com/esp-rs/esp-idf-svc/blob/master/src/log.rs#L15C1-L24
If we comment this part of code, then there is no memory issue.
If the slice length is less than 4, there there is no memory issue too. It's very weird.
```rust
        unsafe {
            let slice = "log\n".as_bytes();
            fwrite(slice.as_ptr() as *const _, 1, slice.len() as u32, stdout);
        }
```

Can anyone help to take a look what's the problem in `EspLogger`?
Thanks. 

[UPDATE]
I remove a log of a task which run every 10ms, then it seems the memory issue doesn't occur.
Maybe we shouldn't log too fast or make too many logs?
