### ISSUE TITLE
no method named `ws_handler` found in EspHttpServer type

### ISSUE THREAD

**Issue by fabracht** [esp-rs/esp-idf-svc#299]
I'm trying to write a WebSocket server using esp-idf-svc 0.46.2.
I created a project using the esp-idf template and followed the "Guess" websocket example, but I can't use the server Web socket functionality. 

For reference:
Here's how I create the server
```rust
fn start_http_server() -> Result<EspHttpServer, Box<dyn std::error::Error>> {
    let conf = HttpConfiguration {
        stack_size: 10240,
        ..Default::default()
    };
    let mut server = EspHttpServer::new(&conf)?;

    server.fn_handler("/", embedded_svc::http::Method::Get, |req| {
        req.into_ok_response()?.write(INDEX_HTML.as_bytes())?;
        Ok(())
    })?;
    server.fn_handler("/*", embedded_svc::http::Method::Get, |req| {
        req.into_status_response(404)?;
        Ok(())
    })?;
    server.ws_handler("/ws", move |ws| {});
    info!("Started http server");
    Ok(server)
}
```

This is my Cargo.toml
```toml
[package]
name = "esp-websocket"
version = "0.1.0"
authors = ["Author"]
edition = "2021"
resolver = "2"
rust-version = "1.71"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]

default = ["std", "hal", "esp-idf-sys/native"]

pio = ["esp-idf-sys/pio"]
all = ["std", "nightly", "experimental", "embassy"]
hal = ["esp-idf-hal", "embedded-svc", "esp-idf-svc"]
std = [
    "alloc",
    "esp-idf-sys/std",
    "esp-idf-sys/binstart",
    "embedded-svc?/std",
    "esp-idf-hal?/std",
    "esp-idf-svc?/std",
]
alloc = ["embedded-svc?/alloc", "esp-idf-hal?/alloc", "esp-idf-svc?/alloc"]
nightly = [
    "embedded-svc?/nightly",
    "esp-idf-svc?/nightly",
] # Future: "esp-idf-hal?/nightly"
experimental = ["embedded-svc?/experimental", "esp-idf-svc?/experimental"]
embassy = [
    "esp-idf-hal?/embassy-sync",
    "esp-idf-hal?/critical-section",
    "esp-idf-hal?/edge-executor",
    "esp-idf-svc?/embassy-time-driver",
    "esp-idf-svc?/embassy-time-isr-queue",
]

[dependencies]
log = { version = "0.4.17", default-features = false }
esp-idf-sys = { version = "0.33", default-features = false }
esp-idf-hal = { version = "0.41", optional = true, default-features = false, features = [
    "esp-idf-sys",
] }
esp-idf-svc = { version = "0.46", optional = true, default-features = true }
embedded-svc = { version = "0.25", optional = true, default-features = false }
embedded-hal = { version = "0.2.7", optional = false, default-features = false }
[build-dependencies]
embuild = "0.31.2"
```

Is there a feature I have to enable somewhere?
