### ISSUE TITLE
Error when running "cargo  build" after running "cargo generate esp-rs/esp-idf-template generate" on Ubuntu

### ISSUE THREAD

**Issue by Spyker2000** [esp-rs/esp-idf-svc#436]
![image](https://github.com/esp-rs/esp-idf-svc/assets/7892368/7d1300e3-8469-490c-8b2b-bf4fae028897)

**Comment by Vollbrecht** [comment]
what ESP_IDF_VERSION are you using? 

Also can you please check if the issue persist with our close to release esp-idf-svc version from git?

You can test them out by adding the following into your Cargo.toml
```toml
[patch.crates-io]
embuild ={ git = "https://github.com/esp-rs/embuild"}
esp-idf-svc ={ git = "https://github.com/esp-rs/esp-idf-svc"}
esp-idf-hal ={ git = "https://github.com/esp-rs/esp-idf-hal"}
esp-idf-sys ={ git = "https://github.com/esp-rs/esp-idf-sys"}
embedded-svc ={ git = "https://github.com/esp-rs/embedded-svc"}
```
and then run `cargo clean` + `cargo update` and then run `cargo build`
