### ISSUE TITLE
How to run examples/http_ws_client.rs with ESP-IDF 5

### ISSUE THREAD

**Issue by omani** [esp-rs/esp-idf-svc#496]
I followed the comment and included the snippet at the end of my `Cargo.toml` file:
```toml
[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp_websocket_client", version = "1.1.0" }
```

but the code does not include anything other than major version 4 with `#[cfg(esp_idf_version_major = "4")]`. so there is no code for version 5 to run.

how exactly am I supposed to run the example code for ESP-IDF >5?
